# Build for amd64 and arm64 and publish to DockerHub and GitHub Packages

name: Build and publish Docker image

on:
  release:
    types: [published]
  push:
    branches: [gmga]

env:
    dockerhub_name: gummigroda

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    #permissions:
    #  packages: write
    #  contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Setup buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      #- name: Log in to the GitHub Packages container registry
      #  uses: docker/login-action@v2
      #  with:
      #    registry: ghcr.io
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.dockerhub_name }}/teslamate-abrp
        # ghcr.io/${{ github.repository }}
      
      - name: Build and push Docker images for releases
        if: github.event_name == 'release'
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }},
            ${{ env.dockerhub_name }}/teslamate-abrp:latest,
        # ghcr.io/${{ github.repository }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Build and push Docker image with 'beta' tag
        if: github.ref == 'refs/heads/gmga'
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ env.dockerhub_name }}/teslamate-abrp:beta,
        # ghcr.io/${{ github.repository }}:beta
          labels: ${{ steps.meta.outputs.labels }}
